### ISSUE TITLE
The uses of `unsafe`

### ISSUE THREAD

**Issue by kellytk** [bastion-rs/bastion#104]
It's unlikely that a project described as "Highly-available Distributed Fault-tolerant Runtime" would prefer to use `unsafe`.  May I ask therefore what criteria its use has within the `bastion` project?

I have an interest in potentially using `bastion` as well in understanding the uses (code) of `unsafe` in the evolution of Rust. (language)

**Comment by azastrael** [comment]
Hey @kellytk :wave:!

Thank you for creating this issue. Your interest and concerns about our use of `unsafe` blocks make perfect sense to us :).

Currently, `bastion` uses `unsafe` in two places: [`system.rs#L75`](https://github.com/bastion-rs/bastion/blob/a7b028d7b18f2d67d801ea5b8a7d5681dc89a2d3/bastion/src/system.rs#L75) and [`system.rs#L86`](https://github.com/bastion-rs/bastion/blob/a7b028d7b18f2d67d801ea5b8a7d5681dc89a2d3/bastion/src/system.rs#L86). This is because we wanted to have an `Option<SupervisorRef>` globally available and initialized only once, at runtime, but without using a lock (to avoid contention and/or unnecessary computations).

This is guaranteed not to be written to more than once and to happen before or when calling `Bastion::init` (which, quick reminder: should be called before using any of Bastion's features ;)).

As for `lightproc` and `bastion-executor`'s use of `unsafe` blocks, there is an ongoing effort at #92 to document all the code more thoroughly. This PR isn't just about the use of `unsafe` but also about making how everything works more understandable for everyone interested in auditing our code or contributing.

This PR hasn't seen much work recently because we wanted to publish `v0.3` before @vertexclique's vacation and, you guessed it, he is currently enjoying his vacations and I am "forced" to work on some non-Bastion-related thinks :D. But, don't worry, we both will get back working on Bastion in the coming days ;).

**Comment by kellytk** [comment]
Thank you @azastrael for your helpful reply.  I appreciate your intent to document the rationale behind uses of `unsafe`.  As that lands I'll have follow-up questions.

**Comment by azastrael** [comment]
No problem @kellytk (and sorry for the late initial reply). I’m looking forward answering those questions :)

Don’t hesitate to join our discord server, if you haven’t already: https://discord.gg/DqRqtRT :D

**Comment by kellytk** [comment]
Thank you for the invitation @azastrael.  Unfortunately I'm unable to use Discord however if you're willing to open a Gitter chat I'd gladly join and participate.

**Comment by kellytk** [comment]
I found the Gitter chat under "bastionframework/community".  Would you accept a PR adding a link to the README?

**Comment by azastrael** [comment]
Thank you @kellytk for proposing this PR. Unfortunately, we would prefer not to have two different chats at the same time. :)

**Comment by azastrael** [comment]
@kellytk I finally got back to working on Bastion (:tada:) and found a way to get rid of the `unsafe` code from the `bastion` crate (+ I added `#![deny(unsafe_code)]` to it :wink:).

**Comment by kellytk** [comment]
@azastrael Excellent.
