### ISSUE TITLE
Potential executor simplification

### ISSUE THREAD

**Issue by kellytk** [bastion-rs/bastion#131]
Tokio is exploring [Structured Concurrency Support](https://github.com/tokio-rs/tokio/issues/1879).  If that's informed by and ultimately accommodates the needs of Bastion its custom executor could potentially be removed.

**Comment by vertexclique** [comment]
Thanks for your suggestion.
 But there are couple of things that needs a spotlight:

1. First this project is not an actor system. This is a runtime since the beginning.
2. Tokio never have offered smth more general (https://github.com/tokio-rs/tokio/issues/1879#issuecomment-564394200) and never going to be. This project USED tokio before, while noone was implementing Erlang like runtime systems. Question comes in mind: "Where they have been?"
3. Absorbing projects and completely copying approaches and their API is not a right approach. (It's easy to say "I didn't understand what it is" if you are copying over)
4. We are using reduction based concurrency control with two phases locking on the current system at a time, and I think they have never heard this before. And I think they will copy that too.
5. Vilification of what other people do (for example, Bastion project) by saying: "Tokio offers more" isn't right. There is no code existing yet at their side.
6. Instead of derogatory comments, they can contact us and improve collaboration. We are open about it.
7. We are not going to remove what is underneath Bastion. A lot of people put a lot of effort into making this, and even it wasn't our day job like Tokio developers. It contains enormous amount of energy and sweat. We aren't done yet. We have just started.

Sidenote for this issue:
Our executor design is way much more straightforward than Tokio's. If they want to care, they can learn from our designs. And I hope next time they can refer to what they are copying as API or code.

**Comment by kellytk** [comment]
@vertexclique Being unfamiliar with both projects I'm unable to address most of your comment.  My thought was that if Tokio's introducing a similar but more generic solution it could be useful to Bastion.  Would you prefer that I close this issue?

**Comment by vertexclique** [comment]
Thank you for your suggestion. There is nothing wrong with your thinking and truly I appreciate that you opened this issue otherwise we won't be aware of this thing. We are implementing the issues that we have talked on lobste.rs and they were very helpful. I think you've already understood the Bastion. For this time of being I want to close this issue.
