### ISSUE TITLE
Dispatch default handle is a silent no-op

### ISSUE THREAD

**Issue by o0Ignition0o** [bastion-rs/bastion#185]
**Is your feature request related to a problem? Please describe.**

As mentioned on discord:

> Doesn't look intuitive for me a default handle is a no op:

https://github.com/bastion-rs/bastion/blob/master/bastion/src/dispatcher.rs#L174

**Describe the solution you'd like**

It would probably make sense to either:
- Warn users they didn’t override the dispatch behavior, so nothing is going to happen
- Do round robin dispatch by default
- maybe both ? (Do round robin and info/warn the default dispatch behavior has been chosen)

What do you think ?

**Comment by Relrin** [comment]
> Warn users they didn’t override the dispatch behavior, so nothing is going to happen
It's totally make sense to me. However, the warning must be displayed once for each instantiated dispatcher with the default behaviour. 

> Do round robin dispatch by default
For this particular we actually have two possible solutions:
1. Provide a default implementation for the [DispatcherHandler](https://github.com/bastion-rs/bastion/blob/aa7af6c58714d6e176e00e2d414d2534919becde/bastion/src/dispatcher.rs#L65-L75`) trait, so that it will be possible to override it when in necessary. If we're going to go with the solution, then there's no sense to put warnings in logs.
2. Implement an additional handler and put it in `dispatcher.rs` module, so that developers could import and reuse it later on.

**Comment by vertexclique** [comment]
I am biased towards to the first solution because of how other systems are working. Like akka:
https://doc.akka.io/docs/akka/current/typed/routers.html#round-robin

**Comment by o0Ignition0o** [comment]
> This is the default for pool routers as the pool of routees is expected to remain the same.

Ok I'm going to give it a try.
